lock.back_door_lock:
  ignored: false
  polling_intensity: 1
lock.front_door_lock:
  ignored: false
  polling_intensity: 0
sensor.front_door_lock_deadbolt:
  ignored: false
  polling_intensity: 0
switch.fireplace:
  ignored: false
  polling_intensity: 1
sensor.schlage_be469_touchscreen_deadbolt_usercode_4:
  ignored: false
  polling_intensity: 1
sensor.schlage_be469_touchscreen_deadbolt_usercode_2:
  ignored: false
  polling_intensity: 1
sensor.schlage_be469_touchscreen_deadbolt_usercode:
  ignored: false
  polling_intensity: 1
